version: "1.0.0"
services:
  backend:
    container_name: api-server
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3080:3080"
    links:
      - database-mongo
    environment:
      - BACK_HOST=localhost
      - BACK_PORT=3080
      - FRONT_HOST=localhost
      - FRONT_PORT=3000
      - TOKEN_SECRET=
      - GITHUB_AUTH_CLIENT_ID=
      - GITHUB_AUTH_CLIENT_SECRET=
      - CLIENT_GITHUB_CALLBACK_URL=http://localhost:3080/api/v1/oauth/github/callback
      - GOOGLE_AUTH_CLIENT_ID=
      - GOOGLE_AUTH_CLIENT_SECRET=
      - CLIENT_GOOGLE_CALLBACK_URL=http://localhost:3080/api/v1/oauth/google/callback
    volumes:
      - .:/home/app
      - /home/app/node_modules
  database-mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - DB_CONNECTION_STRING=mongodb://nico:password@database-mongo:27017/api-server?authSource=admin
      - MONGO_INITDB_ROOT_USERNAME=nico
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: